version: "3.3"

services:
    ngrok:
        image:  s8sg/ngrok
        networks:
            - net
        ports:
            - 6060:6060
        deploy:
            mode: global
            restart_policy:
                condition: on-failure
                delay: 5s
                window: 380s
            placement:
                constraints:
                    - 'node.role == manager'
                    - 'node.platform.os == linux'
            resources:
                limits:
                    memory: 500M
        environment:
                NGROK_PROTOCOL: "http"
                NGROK_PORT: ${ADDRESS}
                NGROK_REGION: "ap"

networks:
    net:
        external:
            name: ${NETWORK}
